### ISSUE TITLE
Possible sub-pages

### ISSUE THREAD

**Issue by BrunoGrandePhD** [brunogrande/guild#2]
We need to come up with a list of possible sub-pages for the theme and their names. Here's a first go at it, based on what I've seen in other lab websites (see #1). 
- Research
- Team
- PI Bio
- Publications
- Software
- Join the Team / Prospective Students
- Photos
- Blog
- Contact

**Comment by santina** [comment]
Mmm... 
Photos and Blog can be merged. 
Join the Team and Contact could be merged too. 
Publications and Softwares can be merged as well.

**Comment by BrunoGrandePhD** [comment]
I agree with merging Contact and Join the Team. I've seen that on other lab websites. However, I have reservations about the other two. 

**Blog and Photos**
- Nesting Photos under Blog might not be discoverable. 
- I'm thinking that for the Photos page, the user can just dump JPG files into a folder and I would display them. If we merge Blog and Photos, the user would have to create a blog post for posting photos, which is more complicated. 
- I can see labs wanting Photos without a Blog. If we merge them, they can't choose one without the other. 

**Publications and Software**

This makes more sense to me, but I do have some concerns. 
- Again, I'm afraid that Software won't be very discoverable under Publications. This could be solved with a different name. Maybe Contributions. 
- Some software exists without being published, so it would be a misclassification to place them under Publications.

**Comment by santina** [comment]
Publications:  Any work that has been done and published, including softwares 
Current Projects:  Any ongoing work, including softwares that are being developed. 

Agree with the point on Blog and Photos

**Comment by BrunoGrandePhD** [comment]
Sounds good! Currently adding:
- Current Projects
- Team
- PI Bio
- Publications
- Blog
- Photos
- Contact
